version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directory: /vendor/github.com/mochi-mqtt/server/v2
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /vendor/go.opentelemetry.io/otel
    schedule:
      interval: daily
