name: CloudEventsIntegration

on:
  workflow_dispatch: {}
  pull_request:
    paths:
     - 'pkg/work/spoke/*.go'
     - 'test/integration/cloudevents/**'
    branches:
      - main
      - release-*

env:
  GO_VERSION: '1.21'
  GO_REQUIRED_MIN_VERSION: ''

permissions:
  contents: read

jobs:
  integration:
    name: cloudevents-integration
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: checkout code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: install Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: integration
        run: make test-cloudevents-integration
