name: E2E

on:
  workflow_dispatch: {}
  pull_request:
    paths-ignore:
      - 'solutions/**'
      - 'assets/**'
      - 'troubleshooting/**'
      - ".github/ISSUE_TEMPLATE/*"
    branches:
      - main
      - release-*

env:
  GO_VERSION: '1.21'
  GO_REQUIRED_MIN_VERSION: ''

permissions:
  contents: read

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Setup Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Setup kind
        uses: engineerd/setup-kind@aa272fe2a7309878ffc2a81c56cfe3ef108ae7d0 # v0.5.0
        with:
          version: v0.17.0
      - name: install imagebuilder
        run: go install github.com/openshift/imagebuilder/cmd/imagebuilder@v1.2.3
      - name: Build images
        run: IMAGE_TAG=e2e make images
      - name: Load images
        run: |
          kind load docker-image --name=kind quay.io/open-cluster-management/registration-operator:e2e
          kind load docker-image --name=kind quay.io/open-cluster-management/registration:e2e
          kind load docker-image --name=kind quay.io/open-cluster-management/work:e2e
          kind load docker-image --name=kind quay.io/open-cluster-management/placement:e2e
          kind load docker-image --name=kind quay.io/open-cluster-management/addon-manager:e2e
      - name: Test E2E
        run: |
          IMAGE_TAG=e2e make test-e2e
        env:
          KUBECONFIG: /home/runner/.kube/config
  e2e-hosted:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Setup Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Setup kind
        uses: engineerd/setup-kind@aa272fe2a7309878ffc2a81c56cfe3ef108ae7d0 # v0.5.0
        with:
          version: v0.17.0
      - name: install imagebuilder
        run: go install github.com/openshift/imagebuilder/cmd/imagebuilder@v1.2.3
      - name: Build images
        run: IMAGE_TAG=e2e make images
      - name: Load images
        run: |
          kind load docker-image --name=kind quay.io/open-cluster-management/registration-operator:e2e
          kind load docker-image --name=kind quay.io/open-cluster-management/registration:e2e
          kind load docker-image --name=kind quay.io/open-cluster-management/work:e2e
          kind load docker-image --name=kind quay.io/open-cluster-management/placement:e2e
          kind load docker-image --name=kind quay.io/open-cluster-management/addon-manager:e2e
      - name: Test E2E
        run: |
          IMAGE_TAG=e2e KLUSTERLET_DEPLOY_MODE=SingletonHosted make test-e2e
        env:
          KUBECONFIG: /home/runner/.kube/config
  e2e-singleton:
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - name: Setup Go
        uses: actions/setup-go@6edd4406fa81c3da01a34fa6f6343087c207a568 # v3.5.0
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Setup kind
        uses: engineerd/setup-kind@aa272fe2a7309878ffc2a81c56cfe3ef108ae7d0 # v0.5.0
        with:
          version: v0.17.0
      - name: install imagebuilder
        run: go install github.com/openshift/imagebuilder/cmd/imagebuilder@v1.2.3
      - name: Build images
        run: IMAGE_TAG=e2e make images
      - name: Load images
        run: |
          kind load docker-image --name=kind quay.io/open-cluster-management/registration-operator:e2e
          kind load docker-image --name=kind quay.io/open-cluster-management/registration:e2e
          kind load docker-image --name=kind quay.io/open-cluster-management/work:e2e
          kind load docker-image --name=kind quay.io/open-cluster-management/placement:e2e
          kind load docker-image --name=kind quay.io/open-cluster-management/addon-manager:e2e
      - name: Test E2E
        run: |
          IMAGE_TAG=e2e KLUSTERLET_DEPLOY_MODE=Singleton make test-e2e
        env:
          KUBECONFIG: /home/runner/.kube/config
